default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] || 'manoel' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'Barcelona@07' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'store_development' %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'store_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'store_production' %>
