default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_development
  username: manoel
  password: Barcelona@07
  host: localhost
  port: 5432

test:
  <<: *default
  database: store_test
  username: manoel
  password: Barcelona@07
  host: localhost
  port: 5432

production:
  <<: *default
  database: store_production
  username: manoel
  password: Barcelona@07
  host: localhost
  port: 5432